// ContactsScreen.kt
// PGPony Android — Phase A0 + A9
//
// Contacts tab UI — shows device contacts with linked PGP keys,
// auto-match, and keyserver discovery. Matches iOS ContactsView.
//
// Phase A9 additions:
//   • Search bar at top of contact list (OutlinedTextField with
//     leading magnifier + trailing X-to-clear), filters both
//     linked and unlinked sections via VM searchQuery state.
//   • ContactAvatar — 44dp/40dp circular avatars on every row,
//     either the device contact photo or a gradient-with-initials
//     fallback. Color of fallback signals linked-vs-unlinked at
//     a glance.
//   • Trust badge per linked key — small icon (HelpOutline /
//     Warning / VerifiedUser / WorkspacePremium) tinted by
//     trust level (gray / yellow / green / blue), matches iOS
//     trustColor mapping.
//   • UnlinkedContactRow "already checked" indicator — when an
//     email is in state.checkedEmails (returned no key on a
//     prior lookup), the search-icon button is replaced with a
//     muted RemoveCircle to avoid re-checking emails the user
//     already knows are empty.

package com.pgpony.android.ui.contacts

import android.Manifest
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.input.ImeAction
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import com.pgpony.android.R
import com.pgpony.android.MainActivity
import com.pgpony.android.contacts.ContactWithKeys
import com.pgpony.android.data.TrustLevel
import com.pgpony.android.ui.components.AlgorithmBadge
import com.pgpony.android.ui.components.ScreenTooltip

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun ContactsScreen(viewModel: ContactsViewModel) {
    val state by viewModel.state.collectAsState()

    val snackbarHostState = remember { SnackbarHostState() }
    LaunchedEffect(state.errorMessage) {
        state.errorMessage?.let { snackbarHostState.showSnackbar(it); viewModel.clearError() }
    }
    LaunchedEffect(state.successMessage) {
        state.successMessage?.let { snackbarHostState.showSnackbar(it); viewModel.clearSuccess() }
    }
    LaunchedEffect(Unit) { viewModel.checkAuthorization() }

    // Phase A9 Fix1 — permission flow now routes through MainActivity
    // because Compose's rememberLauncherForActivityResult is broken on
    // FragmentActivity-hosted activities (request codes generated by
    // the registry exceed FragmentActivity's 16-bit
    // validateRequestPermissionsRequestCode limit and crash with
    // IllegalArgumentException). The helper calls
    // ActivityCompat.requestPermissions with a known small request
    // code and dispatches the result through onRequestPermissionsResult.
    val context = LocalContext.current
    val activity = context as? MainActivity
    val onRequestPermission: () -> Unit = {
        activity?.requestRuntimePermission(Manifest.permission.READ_CONTACTS) { granted ->
            if (granted) viewModel.onPermissionGranted()
        }
    }

    Scaffold(
        snackbarHost = { SnackbarHost(snackbarHostState) },
        topBar = {
            TopAppBar(
                title = { Text(stringResource(R.string.contacts_screen_title)) },
                actions = {
                    if (state.isAuthorized) {
                        var menuExpanded by remember { mutableStateOf(false) }
                        IconButton(onClick = { menuExpanded = true }) {
                            Icon(Icons.Filled.MoreVert, stringResource(R.string.contacts_options_cd))
                        }
                        DropdownMenu(
                            expanded = menuExpanded,
                            onDismissRequest = { menuExpanded = false }
                        ) {
                            DropdownMenuItem(
                                text = { Text(stringResource(R.string.contacts_menu_discover_keys)) },
                                onClick = { menuExpanded = false; viewModel.startBulkScan() },
                                leadingIcon = { Icon(Icons.Filled.TravelExplore, null) },
                                enabled = !state.bulkScanActive
                            )
                            DropdownMenuItem(
                                text = { Text(stringResource(R.string.contacts_menu_auto_match)) },
                                onClick = { menuExpanded = false; viewModel.runAutoMatch() },
                                leadingIcon = { Icon(Icons.Filled.AutoFixHigh, null) }
                            )
                            DropdownMenuItem(
                                text = { Text(stringResource(R.string.contacts_menu_refresh)) },
                                onClick = { menuExpanded = false; viewModel.refreshContacts() },
                                leadingIcon = { Icon(Icons.Filled.Refresh, null) }
                            )
                            HorizontalDivider()
                            DropdownMenuItem(
                                text = { Text(stringResource(R.string.contacts_menu_reset_cache)) },
                                onClick = { menuExpanded = false; viewModel.clearCheckedEmails() },
                                leadingIcon = { Icon(Icons.Filled.ClearAll, null) }
                            )
                        }
                    }
                }
            )
        }
    ) { padding ->
        if (!state.isAuthorized) {
            // Permission request view — uses MainActivity helper
            // (A9 Fix1) instead of the broken Compose launcher.
            PermissionView(
                onRequestPermission = onRequestPermission,
                modifier = Modifier.fillMaxSize().padding(padding)
            )
        } else if (state.isLoading) {
            Box(
                modifier = Modifier.fillMaxSize().padding(padding),
                contentAlignment = Alignment.Center
            ) {
                CircularProgressIndicator()
            }
        } else if (state.contactsList.isEmpty()) {
            EmptyContactsView(
                onRefresh = { viewModel.refreshContacts() },
                modifier = Modifier.fillMaxSize().padding(padding)
            )
        } else {
            ContactsList(state = state, viewModel = viewModel, modifier = Modifier.padding(padding))
        }
    }

    // ── First-visit tooltip (Phase 4) ───────────────────────────────────
    ScreenTooltip(
        tooltipKey = "contacts_import",
        message = stringResource(R.string.contacts_tooltip_import)
    )
}

// ── Permission View ────────────────────────────────────────────────────

@Composable
private fun PermissionView(onRequestPermission: () -> Unit, modifier: Modifier = Modifier) {
    Column(
        modifier = modifier.padding(32.dp),
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.Center
    ) {
        Icon(
            Icons.Filled.ContactPhone,
            contentDescription = null,
            modifier = Modifier.size(64.dp),
            tint = MaterialTheme.colorScheme.onSurfaceVariant.copy(alpha = 0.4f)
        )
        Spacer(modifier = Modifier.height(16.dp))
        Text(stringResource(R.string.contacts_permission_title), style = MaterialTheme.typography.titleLarge)
        Spacer(modifier = Modifier.height(8.dp))
        Text(
            stringResource(R.string.contacts_permission_explainer),
            style = MaterialTheme.typography.bodyMedium,
            color = MaterialTheme.colorScheme.onSurfaceVariant,
            modifier = Modifier.padding(horizontal = 16.dp)
        )
        Spacer(modifier = Modifier.height(24.dp))
        Button(onClick = onRequestPermission) {
            Icon(Icons.Filled.CheckCircle, null, modifier = Modifier.size(18.dp))
            Spacer(modifier = Modifier.width(8.dp))
            Text(stringResource(R.string.contacts_permission_button))
        }
    }
}

// ── Empty State ────────────────────────────────────────────────────────

@Composable
private fun EmptyContactsView(onRefresh: () -> Unit, modifier: Modifier = Modifier) {
    Column(
        modifier = modifier.padding(32.dp),
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.Center
    ) {
        Icon(
            Icons.Filled.PersonOff,
            contentDescription = null,
            modifier = Modifier.size(56.dp),
            tint = MaterialTheme.colorScheme.onSurfaceVariant.copy(alpha = 0.4f)
        )
        Spacer(modifier = Modifier.height(16.dp))
        Text(stringResource(R.string.contacts_empty_title), style = MaterialTheme.typography.titleMedium)
        Text(
            stringResource(R.string.contacts_empty_body),
            style = MaterialTheme.typography.bodyMedium,
            color = MaterialTheme.colorScheme.onSurfaceVariant
        )
        Spacer(modifier = Modifier.height(16.dp))
        OutlinedButton(onClick = onRefresh) {
            Icon(Icons.Filled.Refresh, null, modifier = Modifier.size(16.dp))
            Spacer(modifier = Modifier.width(4.dp))
            Text(stringResource(R.string.contacts_empty_refresh_button))
        }
    }
}

// ── Contacts List ──────────────────────────────────────────────────────

@OptIn(ExperimentalMaterial3Api::class)
@Composable
private fun ContactsList(
    state: ContactsUiState,
    viewModel: ContactsViewModel,
    modifier: Modifier = Modifier
) {
    // Phase A9 — pre-compute filtered sections from the VM state.
    // The derived properties on ContactsUiState do the filtering; we
    // just read them.
    val linked = state.filteredLinkedContacts
    val unlinked = state.filteredUnlinkedContacts
    val noResults = state.searchQuery.isNotBlank() && linked.isEmpty() && unlinked.isEmpty()

    Column(modifier = modifier.fillMaxSize()) {
        // ── Search bar (Phase A9) ─────────────────────────────────────
        //
        // OutlinedTextField with leading magnifier + trailing
        // X-to-clear. Drives ContactsViewModel.searchQuery on each
        // keystroke (instant filter, no debounce — matches iOS
        // .searchable feel). ImeAction.Search dismisses the keyboard
        // when the user hits return; the filter is already applied
        // by then so the dismiss is purely a UX nicety.
        OutlinedTextField(
            value = state.searchQuery,
            onValueChange = { viewModel.setSearchQuery(it) },
            modifier = Modifier
                .fillMaxWidth()
                .padding(horizontal = 16.dp, vertical = 8.dp),
            placeholder = { Text(stringResource(R.string.contacts_search_placeholder)) },
            leadingIcon = {
                Icon(Icons.Filled.Search, contentDescription = null,
                    modifier = Modifier.size(20.dp))
            },
            trailingIcon = {
                if (state.searchQuery.isNotEmpty()) {
                    IconButton(onClick = { viewModel.clearSearchQuery() }) {
                        Icon(Icons.Filled.Clear, contentDescription = stringResource(R.string.contacts_search_clear_cd),
                            modifier = Modifier.size(20.dp))
                    }
                }
            },
            singleLine = true,
            shape = RoundedCornerShape(12.dp),
            keyboardOptions = KeyboardOptions(imeAction = ImeAction.Search)
        )

        // ── List body ─────────────────────────────────────────────────
        LazyColumn(
            modifier = Modifier.fillMaxSize(),
            contentPadding = PaddingValues(horizontal = 16.dp, vertical = 4.dp),
            verticalArrangement = Arrangement.spacedBy(4.dp)
        ) {
            // Bulk scan progress banner — always visible above the
            // filtered list since it represents global state, not a
            // contact row.
            if (state.bulkScanActive || state.bulkScanFinished) {
                item {
                    BulkScanBanner(state, viewModel)
                }
            }

            // Phase A9 — "No results" empty state when the search
            // query matches no contacts in either section. Without
            // this, an unmatchable query would render two empty
            // sections silently.
            if (noResults) {
                item {
                    SearchNoResultsBanner(query = state.searchQuery)
                }
                return@LazyColumn
            }

            // Linked contacts (have PGP keys)
            if (linked.isNotEmpty()) {
                item {
                    Row(
                        verticalAlignment = Alignment.CenterVertically,
                        modifier = Modifier.padding(top = 8.dp, bottom = 4.dp)
                    ) {
                        Icon(Icons.Filled.VerifiedUser, null, tint = Color(0xFF22C55E),
                            modifier = Modifier.size(16.dp))
                        Spacer(modifier = Modifier.width(6.dp))
                        Text(stringResource(R.string.contacts_section_encrypted),
                            style = MaterialTheme.typography.titleSmall,
                            color = Color(0xFF22C55E))
                    }
                }
                items(linked, key = { it.contactId }) { contact ->
                    LinkedContactRow(contact)
                }
            }

            // Unlinked contacts (no PGP keys)
            if (unlinked.isNotEmpty()) {
                item {
                    Row(
                        verticalAlignment = Alignment.CenterVertically,
                        modifier = Modifier.padding(top = 16.dp, bottom = 4.dp)
                    ) {
                        Icon(Icons.Filled.People, null,
                            tint = MaterialTheme.colorScheme.onSurfaceVariant,
                            modifier = Modifier.size(16.dp))
                        Spacer(modifier = Modifier.width(6.dp))
                        Text(stringResource(R.string.contacts_section_other),
                            style = MaterialTheme.typography.titleSmall,
                            color = MaterialTheme.colorScheme.onSurfaceVariant)
                    }
                }
                items(unlinked, key = { it.contactId }) { contact ->
                    // Phase A9 — normalize both the row's first email
                    // and the VM's discoveringEmail for comparison so
                    // mixed-case device contact storage doesn't break
                    // the spinner match. Same normalization is used
                    // for the checkedEmails membership test (the set
                    // is stored lowercased by markEmailChecked).
                    val firstEmail = contact.emails.firstOrNull()
                        ?.lowercase()?.trim()
                    val discoveringNorm = state.discoveringEmail
                        ?.lowercase()?.trim()
                    UnlinkedContactRow(
                        contact = contact,
                        isDiscovering = firstEmail != null
                                && discoveringNorm == firstEmail,
                        isAlreadyChecked = firstEmail != null
                                && firstEmail in state.checkedEmails,
                        onDiscover = { email ->
                            viewModel.discoverKeyForEmail(email, contact.displayName)
                        }
                    )
                }
            }
        }
    }
}

/**
 * Phase A9 — shown inside the LazyColumn when the search query
 * matches no contacts in either section. Inline rather than
 * full-screen because the bulk scan banner above might still
 * need to render alongside it.
 */
@Composable
private fun SearchNoResultsBanner(query: String) {
    Card(
        modifier = Modifier.fillMaxWidth().padding(vertical = 8.dp),
        colors = CardDefaults.cardColors(
            containerColor = MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.3f)
        )
    ) {
        Column(
            modifier = Modifier.fillMaxWidth().padding(16.dp),
            horizontalAlignment = Alignment.CenterHorizontally
        ) {
            Icon(
                Icons.Filled.SearchOff,
                contentDescription = null,
                tint = MaterialTheme.colorScheme.onSurfaceVariant,
                modifier = Modifier.size(32.dp)
            )
            Spacer(modifier = Modifier.height(8.dp))
            Text(
                stringResource(R.string.contacts_search_no_match_format, query),
                style = MaterialTheme.typography.bodyMedium,
                color = MaterialTheme.colorScheme.onSurfaceVariant
            )
        }
    }
}

// ── Bulk Scan Banner ───────────────────────────────────────────────────

@Composable
private fun BulkScanBanner(state: ContactsUiState, viewModel: ContactsViewModel) {
    Card(
        modifier = Modifier.fillMaxWidth().padding(vertical = 4.dp),
        colors = CardDefaults.cardColors(
            containerColor = MaterialTheme.colorScheme.primaryContainer.copy(alpha = 0.3f)
        )
    ) {
        Column(modifier = Modifier.padding(12.dp)) {
            if (state.bulkScanActive) {
                Row(verticalAlignment = Alignment.CenterVertically) {
                    CircularProgressIndicator(modifier = Modifier.size(16.dp), strokeWidth = 2.dp)
                    Spacer(modifier = Modifier.width(8.dp))
                    Text(
                        stringResource(R.string.contacts_scan_in_progress_format, state.bulkScanProgress, state.bulkScanTotal),
                        style = MaterialTheme.typography.bodySmall
                    )
                    Spacer(modifier = Modifier.weight(1f))
                    TextButton(onClick = { viewModel.cancelBulkScan() }) {
                        Text("Cancel", style = MaterialTheme.typography.labelSmall)
                    }
                }
                if (state.bulkScanTotal > 0) {
                    LinearProgressIndicator(
                        progress = { state.bulkScanProgress.toFloat() / state.bulkScanTotal },
                        modifier = Modifier.fillMaxWidth().padding(top = 4.dp)
                    )
                }
            } else if (state.bulkScanFinished) {
                Text(
                    if (state.bulkScanFound == 1) stringResource(R.string.contacts_scan_complete_one_format, state.bulkScanFound) else stringResource(R.string.contacts_scan_complete_many_format, state.bulkScanFound),
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.primary
                )
            }
        }
    }
}

// ── Contact Rows ───────────────────────────────────────────────────────

@Composable
private fun LinkedContactRow(contact: ContactWithKeys) {
    Card(
        modifier = Modifier.fillMaxWidth(),
        colors = CardDefaults.cardColors(
            containerColor = MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.3f)
        )
    ) {
        Column(modifier = Modifier.padding(12.dp)) {
            // Phase A9 — header row: avatar + name/email + "encrypted"
            // green shield. Matches iOS linkedContactRow layout.
            Row(verticalAlignment = Alignment.CenterVertically) {
                ContactAvatar(
                    displayName = contact.displayName,
                    thumbnail = contact.thumbnail,
                    isLinked = true,
                    size = 44.dp
                )
                Spacer(modifier = Modifier.width(12.dp))
                Column(modifier = Modifier.weight(1f)) {
                    Text(
                        contact.displayName,
                        style = MaterialTheme.typography.bodyLarge,
                        maxLines = 1,
                        overflow = TextOverflow.Ellipsis
                    )
                    contact.emails.firstOrNull()?.let { email ->
                        Text(
                            email,
                            style = MaterialTheme.typography.bodySmall,
                            color = MaterialTheme.colorScheme.onSurfaceVariant,
                            maxLines = 1,
                            overflow = TextOverflow.Ellipsis
                        )
                    }
                }
                Icon(
                    Icons.Filled.VerifiedUser,
                    contentDescription = stringResource(R.string.contacts_linked_cd),
                    tint = Color(0xFF22C55E),
                    modifier = Modifier.size(20.dp)
                )
            }

            // Phase A9 — linked key sub-rows now include a trust badge
            // matching the iOS trustColor mapping. Indent (56dp left)
            // mirrors the iOS layout where keys hang under the
            // header content, not the avatar.
            contact.linkedKeys.forEach { key ->
                Row(
                    verticalAlignment = Alignment.CenterVertically,
                    modifier = Modifier.padding(start = 56.dp, top = 4.dp)
                ) {
                    Icon(
                        Icons.Filled.VpnKey,
                        contentDescription = null,
                        modifier = Modifier.size(14.dp),
                        tint = if (key.isKeyPair) Color(0xFF8B5CF6)
                               else MaterialTheme.colorScheme.onSurfaceVariant
                                   .copy(alpha = 0.6f)
                    )
                    Spacer(modifier = Modifier.width(6.dp))
                    AlgorithmBadge(key.algorithm.shortName)
                    Spacer(modifier = Modifier.width(6.dp))
                    Text(
                        key.shortFingerprint,
                        style = MaterialTheme.typography.bodySmall
                            .copy(fontFamily = FontFamily.Monospace),
                        color = MaterialTheme.colorScheme.onSurfaceVariant
                            .copy(alpha = 0.7f)
                    )
                    Spacer(modifier = Modifier.weight(1f))
                    TrustBadge(trust = key.trustLevel)
                }
            }
        }
    }
}

/**
 * Phase A9 — small icon-only badge showing a key's trust level.
 * Mirrors iOS trustColor() + system image mapping:
 *
 *   UNKNOWN    → HelpOutline       (gray)
 *   UNVERIFIED → Warning           (yellow)
 *   VERIFIED   → VerifiedUser      (green — same as the section header)
 *   ULTIMATE   → WorkspacePremium  (blue — premium star icon)
 *
 * 14dp size to match the key icon and algorithm badge inline with
 * the fingerprint row.
 */
@Composable
private fun TrustBadge(trust: TrustLevel) {
    val (icon, tint, label) = when (trust) {
        TrustLevel.UNKNOWN    -> Triple(
            Icons.Filled.HelpOutline,
            MaterialTheme.colorScheme.onSurfaceVariant.copy(alpha = 0.5f),
            stringResource(R.string.contacts_trust_unknown_cd)
        )
        TrustLevel.UNVERIFIED -> Triple(
            Icons.Filled.Warning,
            Color(0xFFEAB308), // yellow-500
            stringResource(R.string.contacts_trust_unverified_cd)
        )
        TrustLevel.VERIFIED   -> Triple(
            Icons.Filled.VerifiedUser,
            Color(0xFF22C55E), // green-500
            stringResource(R.string.contacts_trust_verified_cd)
        )
        TrustLevel.ULTIMATE   -> Triple(
            Icons.Filled.WorkspacePremium,
            Color(0xFF3B82F6), // blue-500
            stringResource(R.string.contacts_trust_ultimate_cd)
        )
    }
    Icon(
        imageVector = icon,
        contentDescription = label,
        tint = tint,
        modifier = Modifier.size(14.dp)
    )
}

@Composable
private fun UnlinkedContactRow(
    contact: ContactWithKeys,
    isDiscovering: Boolean,
    isAlreadyChecked: Boolean,
    onDiscover: (String) -> Unit
) {
    Row(
        modifier = Modifier.fillMaxWidth().padding(vertical = 6.dp),
        verticalAlignment = Alignment.CenterVertically
    ) {
        // Phase A9 — small (40dp) avatar with neutral gradient
        // fallback. Matches iOS unlinkedContactRow.
        ContactAvatar(
            displayName = contact.displayName,
            thumbnail = contact.thumbnail,
            isLinked = false,
            size = 40.dp
        )
        Spacer(modifier = Modifier.width(12.dp))
        Column(modifier = Modifier.weight(1f)) {
            Text(
                contact.displayName,
                style = MaterialTheme.typography.bodyMedium,
                maxLines = 1,
                overflow = TextOverflow.Ellipsis
            )
            contact.emails.firstOrNull()?.let { email ->
                Text(email, style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                    maxLines = 1, overflow = TextOverflow.Ellipsis)
            }
        }
        // Phase A9 — trailing affordance has three states:
        //   • Discovering   → spinner (active keyserver lookup)
        //   • AlreadyChecked → muted minus-circle (no result on a
        //                      prior bulk-scan or single lookup)
        //   • Default       → magnifier IconButton to trigger lookup
        // Matches iOS unlinkedContactRow trailing logic.
        contact.emails.firstOrNull()?.let { email ->
            when {
                isDiscovering -> {
                    CircularProgressIndicator(
                        modifier = Modifier.size(20.dp),
                        strokeWidth = 2.dp
                    )
                }
                isAlreadyChecked -> {
                    // Muted icon with no onClick — clearly signals
                    // "we already looked, no point in trying again".
                    Icon(
                        Icons.Filled.RemoveCircleOutline,
                        contentDescription = stringResource(R.string.contacts_already_checked_cd),
                        tint = MaterialTheme.colorScheme.onSurfaceVariant
                            .copy(alpha = 0.4f),
                        modifier = Modifier.size(20.dp).padding(end = 4.dp)
                    )
                }
                else -> {
                    IconButton(onClick = { onDiscover(email) }) {
                        Icon(Icons.Filled.Search, stringResource(R.string.contacts_search_keyserver_cd),
                            modifier = Modifier.size(20.dp))
                    }
                }
            }
        }
    }
}
