// KeyAlgorithm.kt
// PGPony Android
//
// Matches iOS PGPKeyModel.swift KeyAlgorithm enum.
// Maps OpenPGP algorithm IDs + key versions to our internal enum.

package com.pgpony.android.crypto

/**
 * Key algorithm types supported by PGPony.
 * Matches iOS KeyAlgorithm enum for cross-platform parity.
 */
enum class KeyAlgorithm(
    val displayName: String,
    val shortName: String,
    val keyBits: Int,
    val isV6: Boolean = false
) {
    RSA_2048("RSA 2048", "RSA-2048", 2048),
    RSA_4096("RSA 4096", "RSA-4096", 4096),
    ED25519_CV25519("Ed25519+Cv25519", "Ed25519", 256),

    // RFC 9580 v6 algorithm variants. V6_ED25519 (Ed25519 cert primary +
    // Ed25519 signing subkey + X25519 encryption subkey) is GENERATED by
    // PGPony as of V6-3. The X25519/Ed448/X448 entries remain import-only —
    // they label keys recognized on parse but are not offered for generation.
    V6_ED25519("Ed25519 (v6)", "Ed25519 v6", 256, isV6 = true),
    V6_X25519("X25519 (v6)", "X25519 v6", 256, isV6 = true),
    V6_ED448("Ed448 (v6)", "Ed448 v6", 448, isV6 = true),
    V6_X448("X448 (v6)", "X448 v6", 448, isV6 = true);

    /**
     * Whether this algorithm uses native Curve25519 for encryption (ECDH subkey).
     * Used for routing encrypt/decrypt to the native Cv25519 path vs. RSA.
     */
    val usesCv25519: Boolean
        get() = this == ED25519_CV25519 || this == V6_ED25519 || this == V6_X25519

    companion object {
        /** Algorithms that can be selected in the key generation UI. */
        val generatable = listOf(RSA_2048, RSA_4096, ED25519_CV25519, V6_ED25519)

        /**
         * Map an OpenPGP algorithm ID + key version to a KeyAlgorithm.
         * Handles both v4 (RFC 4880) and v6 (RFC 9580) algorithm IDs.
         *
         * Mirrors iOS KeyAlgorithm.from(algorithmID:keyVersion:).
         */
        fun from(algorithmID: Int, keyVersion: Int = 4): KeyAlgorithm? {
            return if (keyVersion == 6) {
                when (algorithmID) {
                    27 -> V6_ED25519       // Ed25519 signing key
                    25 -> V6_X25519        // X25519 encryption subkey
                    28 -> V6_ED448         // Ed448 signing key
                    26 -> V6_X448          // X448 encryption subkey
                    1, 2, 3 -> RSA_4096    // RSA (can't tell bit size from algo ID)
                    22 -> ED25519_CV25519  // Legacy EdDSA OID — unlikely in v6 but valid
                    18 -> ED25519_CV25519  // Legacy ECDH — unlikely in v6 but valid
                    else -> null
                }
            } else {
                // V4 (RFC 4880)
                when (algorithmID) {
                    1, 2, 3 -> RSA_4096    // RSA — can't tell bit size from algo ID
                    22 -> ED25519_CV25519  // EdDSA (legacy OID-based Ed25519)
                    18 -> ED25519_CV25519  // ECDH (Cv25519 subkey)
                    else -> null
                }
            }
        }
    }
}
