// QRScannerScreen.kt
// PGPony Android — A0 + A10a
//
// CameraX-based QR code scanner using ZXing for decoding. Scans for
// armored PGP keys in QR codes.
//
// Phase A10a — camera permission flow rewired to use
// MainActivity.requestRuntimePermission (the A9 Fix1 helper). The
// pre-A10a code used rememberLauncherForActivityResult with
// ActivityResultContracts.RequestPermission, which crashes on
// FragmentActivity-hosted activities (request codes generated by
// the Compose registry exceed the 16-bit limit FragmentActivity
// enforces). Same fix as ContactsScreen and KeyDetailScreen.

package com.pgpony.android.ui.scanner

import android.Manifest
import android.util.Size
import androidx.camera.core.*
import androidx.camera.lifecycle.ProcessCameraProvider
import androidx.camera.view.PreviewView
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.LocalLifecycleOwner
import androidx.compose.ui.unit.dp
import androidx.compose.ui.viewinterop.AndroidView
import androidx.core.content.ContextCompat
import com.google.zxing.*
import com.google.zxing.common.HybridBinarizer
import com.pgpony.android.R
import com.pgpony.android.MainActivity
import com.pgpony.android.ui.util.rememberHaptics
import java.nio.ByteBuffer
import java.util.concurrent.Executors

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun QRScannerScreen(
    onScanned: (String) -> Unit,
    onDismiss: () -> Unit
) {
    val context = LocalContext.current
    val lifecycleOwner = LocalLifecycleOwner.current
    val haptics = rememberHaptics()
    var hasCameraPermission by remember { mutableStateOf(false) }
    var scanResult by remember { mutableStateOf<String?>(null) }
    var isScanning by remember { mutableStateOf(true) }

    // Phase A10a — permission flow routes through MainActivity helper
    // because Compose's rememberLauncherForActivityResult crashes on
    // FragmentActivity (request codes >16 bits). The helper calls
    // ActivityCompat.requestPermissions with a known small code.
    val activity = context as? MainActivity

    LaunchedEffect(Unit) {
        val permission = ContextCompat.checkSelfPermission(context, Manifest.permission.CAMERA)
        if (permission == android.content.pm.PackageManager.PERMISSION_GRANTED) {
            hasCameraPermission = true
        } else {
            activity?.requestRuntimePermission(Manifest.permission.CAMERA) { granted ->
                hasCameraPermission = granted
            }
        }
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text(stringResource(R.string.qr_scanner_title)) },
                navigationIcon = {
                    IconButton(onClick = onDismiss) {
                        Icon(Icons.Filled.ArrowBack, "Back")
                    }
                }
            )
        }
    ) { padding ->
        if (!hasCameraPermission) {
            Box(
                modifier = Modifier.fillMaxSize().padding(padding),
                contentAlignment = Alignment.Center
            ) {
                Column(horizontalAlignment = Alignment.CenterHorizontally) {
                    Icon(Icons.Filled.CameraAlt, null, modifier = Modifier.size(48.dp),
                        tint = MaterialTheme.colorScheme.onSurfaceVariant.copy(alpha = 0.5f))
                    Spacer(modifier = Modifier.height(16.dp))
                    Text(stringResource(R.string.qr_scanner_permission_title))
                    Spacer(modifier = Modifier.height(8.dp))
                    Button(onClick = {
                        // A10a — same MainActivity helper as the
                        // initial LaunchedEffect request; the
                        // "Grant Permission" button is the user's
                        // way to retry after a previous denial.
                        activity?.requestRuntimePermission(
                            Manifest.permission.CAMERA
                        ) { granted ->
                            hasCameraPermission = granted
                        }
                    }) { Text(stringResource(R.string.qr_scanner_grant_button)) }
                }
            }
        } else {
            Box(modifier = Modifier.fillMaxSize().padding(padding)) {
                // Camera preview
                CameraPreview(
                    isScanning = isScanning,
                    onQRDetected = { text ->
                        if (isScanning) {
                            isScanning = false
                            scanResult = text
                            haptics.success()
                            onScanned(text)
                        }
                    }
                )

                // Scan overlay
                Box(
                    modifier = Modifier.fillMaxSize(),
                    contentAlignment = Alignment.Center
                ) {
                    // Viewfinder frame
                    Box(
                        modifier = Modifier
                            .size(250.dp)
                            .border(2.dp, Color(0xFF8B5CF6), RoundedCornerShape(12.dp))
                    )
                }

                // Bottom hint
                Box(
                    modifier = Modifier.fillMaxSize().padding(bottom = 48.dp),
                    contentAlignment = Alignment.BottomCenter
                ) {
                    Text(
stringResource(R.string.qr_scanner_hint),
                        style = MaterialTheme.typography.bodyMedium,
                        color = Color.White
                    )
                }
            }
        }
    }
}

// ── CameraX Preview with ZXing QR Decoding ─────────────────────────────

@Composable
private fun CameraPreview(
    isScanning: Boolean,
    onQRDetected: (String) -> Unit
) {
    val context = LocalContext.current
    val lifecycleOwner = LocalLifecycleOwner.current
    val executor = remember { Executors.newSingleThreadExecutor() }

    AndroidView(
        factory = { ctx ->
            val previewView = PreviewView(ctx)

            val cameraProviderFuture = ProcessCameraProvider.getInstance(ctx)
            cameraProviderFuture.addListener({
                val cameraProvider = cameraProviderFuture.get()

                val preview = Preview.Builder().build().also {
                    it.surfaceProvider = previewView.surfaceProvider
                }

                val imageAnalysis = ImageAnalysis.Builder()
                    .setTargetResolution(Size(1280, 720))
                    .setBackpressureStrategy(ImageAnalysis.STRATEGY_KEEP_ONLY_LATEST)
                    .build()

                imageAnalysis.setAnalyzer(executor) { imageProxy ->
                    if (isScanning) {
                        val result = decodeQR(imageProxy)
                        if (result != null) {
                            onQRDetected(result)
                        }
                    }
                    imageProxy.close()
                }

                try {
                    cameraProvider.unbindAll()
                    cameraProvider.bindToLifecycle(
                        lifecycleOwner,
                        CameraSelector.DEFAULT_BACK_CAMERA,
                        preview,
                        imageAnalysis
                    )
                } catch (_: Exception) {
                    // Camera binding failed
                }
            }, ContextCompat.getMainExecutor(ctx))

            previewView
        },
        modifier = Modifier.fillMaxSize()
    )
}

/**
 * Decode a QR code from a CameraX ImageProxy using ZXing.
 *
 * Two classic CameraX-with-ZXing failure modes handled here:
 *
 *  1. **Row-stride padding.** CameraX's ImageProxy reports a Y-plane
 *     buffer that may have rowStride > width. The extra bytes per row
 *     are padding the codec/sensor inserts for alignment. PlanarYUVLuminanceSource
 *     expects a tight width × height grid; if we hand it a padded
 *     buffer, the padding bytes get interpreted as luminance and the
 *     QR finder pattern detection fails silently (returns
 *     NotFoundException). We copy each row into a tight buffer below,
 *     skipping the padding columns.
 *
 *  2. **Rotation.** The sensor is landscape; the phone is held portrait.
 *     The Y plane comes out rotated 90° from what the user sees in the
 *     preview, so a portrait-oriented QR code reaches the decoder
 *     sideways. ZXing's QR finder isn't fully rotation-invariant
 *     even with TRY_HARDER. We read imageProxy.imageInfo.rotationDegrees
 *     (set by CameraX based on sensor orientation + target rotation)
 *     and rotate the Y plane to match the display orientation before
 *     decoding. As a safety net we also try the unrotated source if
 *     the rotated one returns NotFound — covers edge cases where the
 *     QR happens to be 90° off in the source image.
 */
private fun decodeQR(imageProxy: ImageProxy): String? {
    val plane = imageProxy.planes[0]
    val buffer = plane.buffer
    val rowStride = plane.rowStride
    val pixelStride = plane.pixelStride
    val width = imageProxy.width
    val height = imageProxy.height

    // Step 1: pull a tight width × height Y-plane out of the (possibly)
    // padded buffer. When rowStride == width AND pixelStride == 1 the
    // buffer is already tight; copy the whole thing in one call.
    // Otherwise walk row by row and skip the padding columns.
    val yPlane = ByteArray(width * height)
    if (rowStride == width && pixelStride == 1) {
        buffer.get(yPlane)
    } else {
        val rowBuf = ByteArray(rowStride)
        for (row in 0 until height) {
            buffer.position(row * rowStride)
            val toRead = minOf(rowStride, buffer.remaining())
            buffer.get(rowBuf, 0, toRead)
            if (pixelStride == 1) {
                System.arraycopy(rowBuf, 0, yPlane, row * width, width)
            } else {
                // pixelStride > 1 only happens on weird YUV layouts;
                // sample every pixelStride-th byte to reconstruct the
                // luminance row.
                var dst = row * width
                var src = 0
                repeat(width) {
                    yPlane[dst++] = rowBuf[src]
                    src += pixelStride
                }
            }
        }
    }

    // Step 2: rotate the Y plane to display orientation. CameraX populates
    // imageInfo.rotationDegrees with the rotation needed to bring sensor
    // output up to the target rotation — usually 90 on a portrait phone
    // with the back camera.
    val rotation = imageProxy.imageInfo.rotationDegrees
    val (rotatedBytes, rotW, rotH) = rotateYPlane(yPlane, width, height, rotation)

    // Try the rotated source first. If decode fails, fall back to the
    // unrotated source — covers the case where the QR in the world
    // happens to be presented at 90° to the phone (laid on a table,
    // displayed on another phone in landscape, etc.).
    decodeYPlane(rotatedBytes, rotW, rotH)?.let { return it }
    if (rotation != 0) {
        decodeYPlane(yPlane, width, height)?.let { return it }
    }
    return null
}

/**
 * Rotate a single-channel (luminance) byte array by 0/90/180/270 degrees
 * clockwise. Returns the rotated bytes plus the new width/height.
 */
private fun rotateYPlane(
    src: ByteArray,
    width: Int,
    height: Int,
    rotation: Int,
): Triple<ByteArray, Int, Int> {
    if (rotation == 0) return Triple(src, width, height)
    val dst = ByteArray(src.size)
    when (rotation) {
        90 -> {
            // Pixel at (x, y) in source → (height-1-y, x) in rotated.
            for (y in 0 until height) {
                val srcRow = y * width
                for (x in 0 until width) {
                    val dstIdx = x * height + (height - 1 - y)
                    dst[dstIdx] = src[srcRow + x]
                }
            }
            return Triple(dst, height, width)
        }
        180 -> {
            val n = src.size
            for (i in 0 until n) dst[i] = src[n - 1 - i]
            return Triple(dst, width, height)
        }
        270 -> {
            for (y in 0 until height) {
                val srcRow = y * width
                for (x in 0 until width) {
                    val dstIdx = (width - 1 - x) * height + y
                    dst[dstIdx] = src[srcRow + x]
                }
            }
            return Triple(dst, height, width)
        }
        else -> return Triple(src, width, height)
    }
}

/** Run ZXing against a tight, correctly-oriented luminance buffer. */
private fun decodeYPlane(yPlane: ByteArray, width: Int, height: Int): String? {
    val source = PlanarYUVLuminanceSource(
        yPlane,
        width,
        height,
        0, 0,
        width,
        height,
        false,
    )
    val binaryBitmap = BinaryBitmap(HybridBinarizer(source))
    return try {
        val hints = mapOf(
            DecodeHintType.POSSIBLE_FORMATS to listOf(BarcodeFormat.QR_CODE),
            DecodeHintType.TRY_HARDER to true,
        )
        MultiFormatReader().decode(binaryBitmap, hints).text
    } catch (_: NotFoundException) {
        null
    } catch (_: Exception) {
        null
    }
}
